modLoader = "javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "Liminal Industries: Russian Translation Audit"
authors = "Petr K."
description = '''Development-only runtime audit for translations and book layouts.'''
displayTest = "IGNORE_ALL_VERSION"
showAsResourcePack = false

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},48)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "jei"
mandatory = true
versionRange = "[${jei_version},16)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "patchouli"
mandatory = true
versionRange = "[${minecraft_version}-${patchouli_version}-FORGE,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "mantle"
mandatory = true
versionRange = "[${mantle_version}]"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "tconstruct"
mandatory = true
versionRange = "[${tconstruct_version}]"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "liminal_industries_ru"
mandatory = true
versionRange = "[${mod_version}]"
ordering = "AFTER"
side = "CLIENT"
