import json
import sys
import tempfile
import unittest
import zipfile
from pathlib import Path


sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from build_resource_packs import (
    load_canonical,
    load_managed_compatibility_assets,
    selected_resources,
    validate_book_recipe_references,
    validate_manifest,
    verify_jar,
)


class ResourcePackSourceTest(unittest.TestCase):
    def test_partitions_language_and_patchouli_resources_together(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            language = root / "assets/example/lang/ru_ru.json"
            patchouli = (
                root
                / "assets/example/patchouli_books/guide/ru_ru/entries/start.json"
            )
            language.parent.mkdir(parents=True)
            patchouli.parent.mkdir(parents=True)
            language.write_text('{"item.example.guide": "Руководство"}', encoding="utf-8")
            patchouli.write_text('{"name": "Начало"}', encoding="utf-8")
            canonical = load_canonical(root)
            manifest = {
                "schema": 1,
                "translation_version": "test",
                "minecraft_version": "1.20.1",
                "packs": [
                    {
                        "id": "example",
                        "display_name": "Example",
                        "target_mod_versions": ["1"],
                        "namespaces": ["example"],
                    }
                ],
            }

            packs = validate_manifest(manifest, "test", canonical)
            selected = selected_resources(packs[0], canonical)

        self.assertEqual(
            {
                "assets/example/lang/ru_ru.json",
                "assets/example/patchouli_books/guide/ru_ru/entries/start.json",
            },
            set(selected),
        )
        self.assertEqual(
            {"name": "Начало"},
            json.loads(
                selected[
                    "assets/example/patchouli_books/guide/ru_ru/entries/start.json"
                ]
            ),
        )

    def test_rejects_autogenerated_kubejs_recipe_ids_in_books(self) -> None:
        files = {
            "assets/example/patchouli_books/guide/en_us/entries/start.json": (
                b'{"pages":[{"type":"crafting",'
                b'"recipe":"example:kjs/a1b2c3d4"}]}'
            )
        }

        with self.assertRaisesRegex(
            ValueError,
            "autogenerated KubeJS recipe ID is not stable",
        ):
            validate_book_recipe_references(files)

    def test_accepts_named_kubejs_recipe_ids_in_books(self) -> None:
        files = {
            "assets/example/patchouli_books/guide/en_us/entries/start.json": (
                b'{"pages":[{"type":"crafting",'
                b'"recipe":"kubejs:fertilizer"}]}'
            )
        }

        validate_book_recipe_references(files)

    def test_jar_partition_ignores_only_internal_book_index(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            language = root / "assets/example/lang/ru_ru.json"
            language.parent.mkdir(parents=True)
            language.write_text('{"item.example": "Пример"}', encoding="utf-8")
            canonical = load_canonical(root)
            jar = root / "translation.jar"
            with zipfile.ZipFile(jar, "w") as archive:
                archive.write(
                    language,
                    "assets/example/lang/ru_ru.json",
                )
                archive.writestr(
                    "assets/liminal_industries_ru/book-translations.json",
                    '{"schema":1,"resources":[]}',
                )

            verify_jar(jar, canonical)

    def test_jar_partition_includes_managed_english_compatibility(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            payload = root / "payload"
            language = payload / "assets/example/lang/ru_ru.json"
            language.parent.mkdir(parents=True)
            language.write_text('{"item.example": "Пример"}', encoding="utf-8")
            canonical = load_canonical(payload)

            compatibility = root / "compatibility"
            english = (
                compatibility
                / "assets/example/books/en_us/entry.json"
            )
            english.parent.mkdir(parents=True)
            english.write_text('{"pages":[]}', encoding="utf-8")
            russian = (
                compatibility
                / "assets/example/books/ru_ru/entry.json"
            )
            russian.parent.mkdir(parents=True)
            russian.write_text('{"pages":[]}', encoding="utf-8")

            managed = load_managed_compatibility_assets(compatibility)
            self.assertEqual(
                {"assets/example/books/en_us/entry.json"},
                set(managed),
            )

            jar = root / "translation.jar"
            with zipfile.ZipFile(jar, "w") as archive:
                archive.write(
                    language,
                    "assets/example/lang/ru_ru.json",
                )
                archive.write(
                    english,
                    "assets/example/books/en_us/entry.json",
                )

            verify_jar(jar, canonical, compatibility)


if __name__ == "__main__":
    unittest.main()
